apiVersion: application-networking.k8s.aws/v1alpha1
kind: ServiceExport
metadata:
  name: nginx-red
  annotations:
    application-networking.k8s.aws/federation: "amazon-vpc-lattice"
spec:
  exportedPorts:
  - port: 80
    routeType: HTTP
